permalink: /:title/
plugins:
  - jekyll-sitemap

title: veerbia.com
url: https://veerbia.com
baseurl: ""
description: "The personal website of Veer Bhatia"
author: Veer
twitter: veerbia
stackoverflow: 1480784/veerbia
linkedin: veerbhatia
hackernews: veerbia
youtube: UCiU3oTGKL4GDr5xgK_EMjnQ
username: veerbia
email: aveerbia@gmail.com

timezone: Pacific
google_analytics_tracking_id: UA-39520634-1
